// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebEntities;

namespace WebEntities.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210826001905_Int")]
    partial class Int
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("WebEntities.Models.Competitions.Competition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ToPay")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("WebEntities.Models.Competitions.CompetitionAttendance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<bool>("HasPayedBool")
                        .HasColumnType("boolean");

                    b.Property<int>("TraineeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("EventID");

                    b.HasIndex("TraineeID");

                    b.ToTable("CompetitionAttendances");
                });

            modelBuilder.Entity("WebEntities.Models.Competitions.CompetitionPayment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("AttendanceID")
                        .HasColumnType("integer");

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PayedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TraineeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AttendanceID");

                    b.HasIndex("EventID");

                    b.HasIndex("TraineeID");

                    b.ToTable("CompetitionPayments");
                });

            modelBuilder.Entity("WebEntities.Models.PayedEvents.PayedEvent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ToPay")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("PayedEvents");
                });

            modelBuilder.Entity("WebEntities.Models.PayedEvents.PayedEventAttendance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<bool>("HasPayedBool")
                        .HasColumnType("boolean");

                    b.Property<int>("TraineeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("EventID");

                    b.HasIndex("TraineeID");

                    b.ToTable("PayedEventAttendances");
                });

            modelBuilder.Entity("WebEntities.Models.PayedEvents.PayedEventPayment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("AttendanceID")
                        .HasColumnType("integer");

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PayedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TraineeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AttendanceID");

                    b.HasIndex("EventID");

                    b.HasIndex("TraineeID");

                    b.ToTable("PayedEventPayments");
                });

            modelBuilder.Entity("WebEntities.Models.Trainee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte?>("Age")
                        .HasColumnType("smallint");

                    b.Property<byte>("AgeGroup")
                        .HasColumnType("smallint");

                    b.Property<byte?>("BeltColor")
                        .HasColumnType("smallint");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("Trainees");
                });

            modelBuilder.Entity("WebEntities.Models.Trainings.Training", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<byte>("AgeGroup")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ToPay")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("WebEntities.Models.Trainings.TrainingAttendance", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<bool>("HasPayedBool")
                        .HasColumnType("boolean");

                    b.Property<int>("TraineeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("EventID");

                    b.HasIndex("TraineeID");

                    b.ToTable("TrainingAttendance");
                });

            modelBuilder.Entity("WebEntities.Models.Trainings.TrainingPayment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("AttendanceID")
                        .HasColumnType("integer");

                    b.Property<int>("EventID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PayedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SpanPayedStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("TimePayed")
                        .HasColumnType("interval");

                    b.Property<int>("TraineeID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("AttendanceID");

                    b.HasIndex("EventID");

                    b.HasIndex("TraineeID");

                    b.ToTable("TrainingPayments");
                });

            modelBuilder.Entity("WebEntities.Models.Competitions.CompetitionAttendance", b =>
                {
                    b.HasOne("WebEntities.Models.Competitions.Competition", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEntities.Models.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("WebEntities.Models.Competitions.CompetitionPayment", b =>
                {
                    b.HasOne("WebEntities.Models.Competitions.CompetitionAttendance", "Attendance")
                        .WithMany("Payments")
                        .HasForeignKey("AttendanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEntities.Models.Competitions.Competition", "Event")
                        .WithMany("Payments")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEntities.Models.Trainee", "Trainee")
                        .WithMany("CompetitionPayment")
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("Event");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("WebEntities.Models.PayedEvents.PayedEventAttendance", b =>
                {
                    b.HasOne("WebEntities.Models.PayedEvents.PayedEvent", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEntities.Models.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("WebEntities.Models.PayedEvents.PayedEventPayment", b =>
                {
                    b.HasOne("WebEntities.Models.PayedEvents.PayedEventAttendance", "Attendance")
                        .WithMany("Payments")
                        .HasForeignKey("AttendanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEntities.Models.PayedEvents.PayedEvent", "Event")
                        .WithMany("Payments")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEntities.Models.Trainee", "Trainee")
                        .WithMany("PayedEventPayments")
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("Event");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("WebEntities.Models.Trainings.TrainingAttendance", b =>
                {
                    b.HasOne("WebEntities.Models.Trainings.Training", "Event")
                        .WithMany("Attendances")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEntities.Models.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("WebEntities.Models.Trainings.TrainingPayment", b =>
                {
                    b.HasOne("WebEntities.Models.Trainings.TrainingAttendance", "Attendance")
                        .WithMany("Payments")
                        .HasForeignKey("AttendanceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEntities.Models.Trainings.Training", "Event")
                        .WithMany("Payments")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebEntities.Models.Trainee", "Trainee")
                        .WithMany("TrainingPayments")
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");

                    b.Navigation("Event");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("WebEntities.Models.Competitions.Competition", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebEntities.Models.Competitions.CompetitionAttendance", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebEntities.Models.PayedEvents.PayedEvent", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebEntities.Models.PayedEvents.PayedEventAttendance", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebEntities.Models.Trainee", b =>
                {
                    b.Navigation("CompetitionPayment");

                    b.Navigation("PayedEventPayments");

                    b.Navigation("TrainingPayments");
                });

            modelBuilder.Entity("WebEntities.Models.Trainings.Training", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebEntities.Models.Trainings.TrainingAttendance", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
